### ISSUE TITLE
can input future intake and history pages shown too

### ISSUE THREAD

**Issue by Tezigudo** [Aquaholic-ISP/Aquaholic#37]
![image](https://user-images.githubusercontent.com/80502090/203462039-d537d24a-6f67-4863-96f7-12a59c6794cf.png)

![image](https://user-images.githubusercontent.com/80502090/203462155-11286e46-28e1-4abb-810c-f14f298966e7.png)

**Comment by kulisarawiangin** [comment]
I already fix it.
3fa5306f5400dbd8b2dc12622a6f6e0e0d5d43c7
