### ISSUE TITLE
graph in history page is small(not full screen)

### ISSUE THREAD

**Issue by Tezigudo** [Aquaholic-ISP/Aquaholic#38]
When you minimize page and fullscreen again table bug(its doesnt full screen)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80502090/203463158-4b5d574a-f690-4bbf-9c18-ffb335a68b77.png">

**Comment by PloyyNK** [comment]
Already fix the position in this commit c38bce921a14c7a76124e41f9086d6415595b79a
