### ISSUE TITLE
Input page, user can input 0 ml of water drank

### ISSUE THREAD

**Issue by Halcyon905** [Aquaholic-ISP/Aquaholic#39]
When the user does not click one of the icons and does not input amount manually, the user can still press save

**Comment by Siripa-Maneein** [comment]
This is not a functionality defect actually as we intentionally allow user to input 0 and make it as a default value. We think 0 is a good number to start and when saved, it does not affect any data saved in the database. However, we have changed the message shown to inform user to input amount more than 0 just to remind that he doesn't input any amount yet in this commit fa5588e267fbc3c2c5abd18e916b38d178f1161a.

**Comment by Siripa-Maneein** [comment]
Thank you.
