### ISSUE TITLE
Spamming save button on input page its send multiple values instead of one.

### ISSUE THREAD

**Issue by koonwill** [Aquaholic-ISP/Aquaholic#40]
![image](https://user-images.githubusercontent.com/93331101/203484575-af528632-e910-438c-856c-51cf448bec63.png)
![image](https://user-images.githubusercontent.com/93331101/203484613-a0e6c417-2e0c-4241-8901-a7133b956a19.png)

**Comment by jindasy** [comment]
Fixed #40 with commit c98c4ab75f4c6ceaa56c6cc21ec10943b0fc2ae8
