### ISSUE TITLE
If I put large amount of time(1844674407370955161518446744073709551615) in set schedule. It make sever error

### ISSUE THREAD

**Issue by MarojT** [Aquaholic-ISP/Aquaholic#43]
![image](https://user-images.githubusercontent.com/59698469/203695879-30f3171b-34b0-40cc-bbf0-2364db24dee9.png)
![image](https://user-images.githubusercontent.com/59698469/203695831-e84ab3f5-bf65-44dd-8695-cc1c85fa8599.png)

**Comment by kulisarawiangin** [comment]
2d01e606a04ec20be20066ba321618c7aa3aadda
I'm already fix it.
