### ISSUE TITLE
My notification is still being sent.

### ISSUE THREAD

**Issue by dzptahh** [Aquaholic-ISP/Aquaholic#55]
I turned off notification but the still being sent
PS. I turned off on November 25, 2022.

<img width="1440" alt="ภาพถ่ายหน้าจอ 2565-11-26 เวลา 21 34 46" src="https://user-images.githubusercontent.com/92835393/204094403-94a38189-74ac-4d1e-bbca-f0a185e251e9.png">
<img width="680" alt="ภาพถ่ายหน้าจอ 2565-11-26 เวลา 21 40 50" src="https://user-images.githubusercontent.com/92835393/204094495-6e07a970-9958-4bae-aa97-345f1acc2ff6.png">

**Comment by Siripa-Maneein** [comment]
I think you can turn off the notification now. Please, make sure that when turning off, there will be no blue round box. I already fixed the logic of the sending method in this commit 74ae68d7a2b000b4d4546f4ebdb62eaf127f7745, but it might take some time to test it thoroughly. If there's still a problem, please let us know. Thank you.
